"""update user table

Revision ID: 14ad8746e5bb
Revises: 2303bcbe57e5
Create Date: 2025-08-19 15:44:00.147029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ad8746e5bb'
down_revision = '2303bcbe57e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
